#!/usr/bin/env python3
"""Generate docs/API.md from the standard library: public functions, structs and enums with
the comment lines just above them."""
import os, re, glob

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SECTIONS = [
    ("core", "Core (always available)"),
    ("std", "Parallelism"),
    ("game", "Games: windows, input, 2D/3D drawing, GPU programs, audio"),
]
def signature(line):
    """the declaration up to the ':' that starts the body (depth-aware)"""
    depth = 0
    for i, c in enumerate(line):
        if c in "([": depth += 1
        elif c in ")]": depth -= 1
        elif c == ":" and depth == 0 and i > 0:
            return line[:i]
    return line


out = ["# Jot standard library reference", "",
       "Generated by `tools/apidoc.py` from the library sources. Everything listed is available",
       "without imports. Functions can be called as `f(x, y)` or `x.f(y)`.", ""]
for sub, title in SECTIONS:
    out.append(f"## {title}")
    out.append("")
    for path in sorted(glob.glob(os.path.join(ROOT, "lib", sub, "*.jot"))):
        lines = open(path).read().splitlines()
        header = []
        for l in lines:
            if l.startswith("#"): header.append(l.lstrip("# ").rstrip())
            else: break
        entries = []
        comment = []
        depth_skip = False
        for l in lines:
            s = l.rstrip()
            if s.startswith("#"):
                c = s.lstrip("# ").rstrip()
                if not re.fullmatch(r"-+.*-+", c): comment.append(c)
                continue
            m = re.match(r"(?:@\w+(?:\([^)]*\))?\s*)?(fn|struct|enum|const)\s+([A-Za-z_][\w]*|[-+*/%<>=!\[\]]+)(.*)", s)
            if m and not s.startswith(" ") and not m.group(2).startswith("__"):
                kind, name, rest = m.groups()
                sig = s
                if kind == "fn":
                    sig = signature(s)
                elif kind in ("struct", "enum"):
                    sig = s.split(":")[0] if kind == "struct" else s
                entries.append((sig.strip(), " ".join(c for c in comment if c)))
            if not s.startswith("#"):
                comment = []
        if not entries: continue
        out.append(f"### {os.path.basename(path)}")
        if header:
            out.append("")
            out.extend(h + "  " for h in header)
        out.append("")
        out.append("```")
        for sig, doc in entries:
            out.append(sig + (f"    # {doc}" if doc else ""))
        out.append("```")
        out.append("")
open(os.path.join(ROOT, "docs", "API.md"), "w").write("\n".join(out) + "\n")
print("wrote docs/API.md")
